name: CI/CD
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      
    - name: INSTALL
      run: npm install
      
    - name: DEVELOP
      if: ${{github.ref != 'refs/heads/master'}}
      run: npm run build
      
    - name: MASTER
      if: ${{github.ref == 'refs/heads/master'}}
      run: npm run build:prod

    - name: DEPLOY
      if: ${{github.ref == 'refs/heads/master' && github.event_name == 'push'}}
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      
      
    
